

all:
	./runtest.sh ../dwarfdump

clean:
	rm -f testincorrecta	       
	rm -f testincorrectbeforechild   
	rm -f testincorrectnest2
	rm -f testincorrectatchild   
	rm -f testincorrectbeforeitself
	rm -f testincorrectatitself  
	rm -f testincorrectnest
	rm -f junk*

distclean: clean
