#!/bin/sh
# Pick up newly built dwarfdump in two flavors.
# Pick up libdwarf in two flavors.
set -x
# Fix the following line to match the desired libdwarf/dwarfdump source 
# directory.
. ./BASEFILES

(cd $libdw/libdwarf; ./configure  --enable-oldframecol ; make clean ; make  )
cp $libdw/libdwarf/libdwarf.a libdwoldframecol.a

(cd $libdw/libdwarf; ./configure  --enable-windowspath; make clean ; make  )
(cd $libdw/dwarfdump ; ./configure ; rm dwarfdump ; make)
cp $libdw/dwarfdump/dwarfdump   dwarfdumpW

(cd $libdw/libdwarf;      make clean;  ./configure ; make clean ; make )
cp $libdw/libdwarf/libdwarf.a libdwarf.a
(cd $libdw/dwarfdump ;    make clean ; ./configure ; make clean ; make)
(cd $libdw/dwarfgen ;     make clean ; ./configure ; make clean ; make)
(cd $libdw/dwarfexample ; make clean ; ./configure ; make clean ; make)

cp $libdw/dwarfdump/dwarfdump  .
cp $libdw/dwarfdump/dwarfdump.conf  .
cp $libdw/libdwarf/gennames .
cp $libdw/dwarfgen/dwarfgen .
cp $libdw/dwarfexample/simplereader .
